version: '3'

services:
  docker-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db
      - MYSQL_USER=lucas
      - MYSQL_PASSWORD=123
    ports:
      - 10000:3306

  app:
    image: spring-app
    ports:
       - 8080:8080
    depends_on:
       - docker-mysql